version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: unless-stopped
  database:
    image: mongo
    expose:
      - "27017"
    restart: unless-stopped
